### ISSUE TITLE
Can not build on redHat 7

### ISSUE THREAD

**Issue by Program-Bear** [y-scope/clp-core#1]
I am trying to build CLP on Linux server(redHat 7), but I encountered CMake(version: 3.21.1) build failure. The debug messages refer it could not find Boost (missing iostreams, program_options filesystem system). But I have libboost-iostreams.a,  libboost-program_options.a, libboost-filesystem.a and libboost-system.a(all are in version 1.59.0)  under /usr/include/lib/, I wonder why the Cmake program could not find them. 
I am looking forward to a solution, thanks.

**Comment by kirkrodrigues** [comment]
Hey @Program-Bear,

First, could you clear the cmake cache in the build folder (`rm CMakeCache.txt`) and then try again to see if you get the same error? (After installing new libraries, etc., sometimes the cmake cache needs to be forcibly refreshed.)

Did you install boost from source or from a RHEL package? When I install from [source](https://www.boost.org/doc/libs/1_76_0/more/getting_started/unix-variants.html), cmake seems to be able to locate the Boost packages.

One thing you could try is to add the directory containing Boost's includes and libs to `CMakeLists.txt:49`. Assuming that's `/usr/include` for you, the line should be:
`find_package(Boost REQUIRED iostreams program_options filesystem system PATHS /usr/include)`
Then clear the cmake cache and retry.

**Comment by Program-Bear** [comment]
Thanks for your response, I have solved this problem with a new version of Boost(at least Boost 1.76)
