### ISSUE TITLE
Fail to compile CLP

### ISSUE THREAD

**Issue by Program-Bear** [y-scope/clp-core#2]
I have met another compilation problem when I try to execute "make" command. It refers missing "xmlReaderForIO" in libarchive.a, I wonder why ? I have "libxml2.a" installed in my lib directory.

**Comment by kirkrodrigues** [comment]
Hey @Program-Bear,

Sorry about that. This is likely due to an issue with our cmake script for setting LibArchive's required compilation flags. I'm working on a fix and will let you know when it's committed.

**Comment by kirkrodrigues** [comment]
In the meantime, you may be able to get it compiled without static linking:
```
cd build
rm CMakeCache.txt
cmake -DCLP_USE_STATIC_LIBS=OFF ../
make
```

**Comment by kirkrodrigues** [comment]
Hey @Program-Bear, could you try the fix I just pushed and see if it resolves the issue?

```
cd build
rm CMakeCache.txt
cmake ../
make
```

**Comment by Program-Bear** [comment]
Thanks for your dedicated work, it works finally!
