### ISSUE TITLE
Centos7.4 build failed

### ISSUE THREAD

**Issue by woxiang-H** [y-scope/clp-core#4]
**All dependencies have been successfully compiled and installed. But an error is reported when make is executed, and the error message is as follows：**
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_read_support_filter_lz4.c.o): in function `lz4_filter_read_legacy_stream':
archive_read_support_filter_lz4.c:(.text+0x1f9): undefined reference to `LZ4_decompress_safe'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_read_support_filter_lz4.c.o): in function `lz4_filter_read_default_stream':
archive_read_support_filter_lz4.c:(.text+0x575): undefined reference to `LZ4_decompress_safe_usingDict'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: archive_read_support_filter_lz4.c:(.text+0x79e): undefined reference to `LZ4_decompress_safe'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_cryptor.c.o): in function `aes_ctr_release':
archive_cryptor.c:(.text+0x18): undefined reference to `EVP_CIPHER_CTX_free'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_cryptor.c.o): in function `aes_ctr_init':
archive_cryptor.c:(.text+0x4e): undefined reference to `EVP_CIPHER_CTX_new'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: archive_cryptor.c:(.text+0x89): undefined reference to `EVP_aes_192_ecb'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: archive_cryptor.c:(.text+0xb7): undefined reference to `EVP_CIPHER_CTX_init'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: archive_cryptor.c:(.text+0xc9): undefined reference to `EVP_aes_128_ecb'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: archive_cryptor.c:(.text+0xd9): undefined reference to `EVP_aes_256_ecb'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_cryptor.c.o): in function `aes_ctr_update':
archive_cryptor.c:(.text+0x2f9): undefined reference to `EVP_EncryptInit_ex'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: archive_cryptor.c:(.text+0x318): undefined reference to `EVP_EncryptUpdate'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_hmac.c.o): in function `__hmac_sha1_cleanup':
archive_hmac.c:(.text+0x10): undefined reference to `HMAC_CTX_cleanup'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_hmac.c.o): in function `__hmac_sha1_final':
archive_hmac.c:(.text+0x48): undefined reference to `HMAC_Final'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_hmac.c.o): in function `__hmac_sha1_init':
archive_hmac.c:(.text+0x95): undefined reference to `EVP_sha1'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: archive_hmac.c:(.text+0xa9): undefined reference to `HMAC_Init_ex'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /usr/local/lib/libarchive.a(archive_hmac.c.o): in function `__hmac_sha1_update':
archive_hmac.c:(.text+0x64): undefined reference to `HMAC_Update'
collect2: error: ld returned 1 exit status
make[2]: *** [clp] mistake 1
make[1]: *** [CMakeFiles/clp.dir/all] mistake 2
make: *** [all] mistake 2

**Comment by kirkrodrigues** [comment]
Hi @woxiang-H,

I think this might be because pkg-config is not finding the packages installed from source.

Can you try this in the build directory?
```
export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH}
rm CMakeCache.txt
cmake ../
make
```

I've also added [docker config files](https://github.com/y-scope/clp-core/tree/main/tools/docker-images/clp-env-base-centos7.4) for building CLP in a CentOS 7.4 container. You could refer to the steps in the Dockerfile to see if our environments match.

**Comment by woxiang-H** [comment]
Thank you for your reply. I built a container image based on the Dockerfile you provided and compiled it successfully in the container.
